/* global process, console */
const path = require('path')
const fs = require('fs')

const CONTRACTS_DIR = path.join(process.cwd(), 'src/contracts')
const OUTPUT_FILE = path.join(process.cwd(), 'src/contracts/index.ts')

/**
 * Extract struct types from a TypeChain generated file
 * Looks for exported type definitions like PaymentRequestStruct, MultisigAuthStruct, etc.
 */
function extractStructTypes(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8')
  const structTypes = []

  // Match exported struct types (e.g., "export type PaymentRequestStruct = {")
  const structRegex = /export\s+type\s+(\w+Struct(?:Output)?)\s*=/g
  let match

  while ((match = structRegex.exec(content)) !== null) {
    structTypes.push(match[1])
  }

  return structTypes
}

/**
 * Get all contract files (excluding common.ts, index.ts, and factories)
 */
function getContractFiles() {
  const files = fs.readdirSync(CONTRACTS_DIR)
  return files.filter(
    (file) => file.endsWith('.ts') && file !== 'index.ts' && file !== 'common.ts' && !file.includes('factory')
  )
}

/**
 * Generate the index.ts file with all exports
 */
function generateExports() {
  const contractFiles = getContractFiles()

  let output = `/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
`

  // First, re-export everything from the original index (contracts and factories)
  // We need to read the original exports and include them
  const originalIndexPath = path.join(CONTRACTS_DIR, 'index.ts')
  if (fs.existsSync(originalIndexPath)) {
    const originalContent = fs.readFileSync(originalIndexPath, 'utf-8')
    // Extract export lines (excluding the header comments)
    const exportLines = originalContent.split('\n').filter((line) => line.startsWith('export'))
    output += exportLines.join('\n') + '\n\n'
  }

  // Collect struct types from each contract file
  const allStructTypes = {}

  for (const file of contractFiles) {
    const contractName = file.replace('.ts', '')
    const filePath = path.join(CONTRACTS_DIR, file)
    const structTypes = extractStructTypes(filePath)

    if (structTypes.length > 0) {
      allStructTypes[contractName] = structTypes
    }
  }

  // Generate struct type exports
  if (Object.keys(allStructTypes).length > 0) {
    output += '// Re-export struct types from contracts\n'

    for (const [contractName, types] of Object.entries(allStructTypes)) {
      const typesList = types.map((t) => `  ${t}`).join(',\n')
      output += `export type {\n${typesList},\n} from './${contractName}'\n\n`
    }
  }

  return output
}

function main() {
  // Ensure contracts directory exists
  if (!fs.existsSync(CONTRACTS_DIR)) {
    console.error(`Contracts directory not found: ${CONTRACTS_DIR}`)
    console.error('Run "yarn typechain" first to generate contract types.')
    process.exit(1)
  }

  const output = generateExports()
  fs.writeFileSync(OUTPUT_FILE, output)
  console.log('Types have been generated successfully!')
  console.log(`Output: ${OUTPUT_FILE}`)
}

main()
