/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

import type {
  AddressLike,
  BaseContract,
  BigNumberish,
  BytesLike,
  ContractMethod,
  ContractRunner,
  EventFragment,
  FunctionFragment,
  Interface,
  Listener,
  Result,
} from 'ethers'

import type {
  TypedContractEvent,
  TypedContractMethod,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedLogDescription,
} from './common'

export type PaymentRequestStruct = {
  token: AddressLike
  amount: BigNumberish
  externalCall: BytesLike
}

export type PaymentRequestStructOutput = [token: string, amount: bigint, externalCall: string] & {
  token: string
  amount: bigint
  externalCall: string
}

export type MultisigAuthStruct = {
  deadline: BigNumberish
  threshold: BigNumberish
  signatures: BytesLike[]
}

export type MultisigAuthStructOutput = [deadline: bigint, threshold: bigint, signatures: string[]] & {
  deadline: bigint
  threshold: bigint
  signatures: string[]
}

export interface OptimexLiquidatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'MIN_REQUIRED_SIGNATURES'
      | 'deposit'
      | 'eip712Domain'
      | 'getProtocol'
      | 'liquidationGateway'
      | 'optimexDomain'
      | 'pause'
      | 'paused'
      | 'payment'
      | 'setGateway'
      | 'setProtocol'
      | 'unpause'
      | 'withdraw'
  ): FunctionFragment

  getEvent(
    nameOrSignatureOrTopic:
      | 'Deposit'
      | 'EIP712DomainChanged'
      | 'LiquidationGatewayUpdated'
      | 'Paused'
      | 'ProtocolUpdated'
      | 'Unpaused'
      | 'Withdraw'
  ): EventFragment

  encodeFunctionData(functionFragment: 'MIN_REQUIRED_SIGNATURES', values?: undefined): string
  encodeFunctionData(functionFragment: 'deposit', values: [AddressLike, BigNumberish]): string
  encodeFunctionData(functionFragment: 'eip712Domain', values?: undefined): string
  encodeFunctionData(functionFragment: 'getProtocol', values?: undefined): string
  encodeFunctionData(functionFragment: 'liquidationGateway', values?: undefined): string
  encodeFunctionData(functionFragment: 'optimexDomain', values?: undefined): string
  encodeFunctionData(functionFragment: 'pause', values?: undefined): string
  encodeFunctionData(functionFragment: 'paused', values?: undefined): string
  encodeFunctionData(functionFragment: 'payment', values: [PaymentRequestStruct, MultisigAuthStruct]): string
  encodeFunctionData(functionFragment: 'setGateway', values: [AddressLike]): string
  encodeFunctionData(functionFragment: 'setProtocol', values: [AddressLike]): string
  encodeFunctionData(functionFragment: 'unpause', values?: undefined): string
  encodeFunctionData(functionFragment: 'withdraw', values: [AddressLike, BigNumberish, AddressLike]): string

  decodeFunctionResult(functionFragment: 'MIN_REQUIRED_SIGNATURES', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'eip712Domain', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getProtocol', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'liquidationGateway', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'optimexDomain', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'payment', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setGateway', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setProtocol', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result
}

export namespace DepositEvent {
  export type InputTuple = [sender: AddressLike, token: AddressLike, amount: BigNumberish]
  export type OutputTuple = [sender: string, token: string, amount: bigint]
  export interface OutputObject {
    sender: string
    token: string
    amount: bigint
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
  export type Filter = TypedDeferredTopicFilter<Event>
  export type Log = TypedEventLog<Event>
  export type LogDescription = TypedLogDescription<Event>
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = []
  export type OutputTuple = []
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
  export type Filter = TypedDeferredTopicFilter<Event>
  export type Log = TypedEventLog<Event>
  export type LogDescription = TypedLogDescription<Event>
}

export namespace LiquidationGatewayUpdatedEvent {
  export type InputTuple = [operator: AddressLike, gateway: AddressLike]
  export type OutputTuple = [operator: string, gateway: string]
  export interface OutputObject {
    operator: string
    gateway: string
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
  export type Filter = TypedDeferredTopicFilter<Event>
  export type Log = TypedEventLog<Event>
  export type LogDescription = TypedLogDescription<Event>
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike]
  export type OutputTuple = [account: string]
  export interface OutputObject {
    account: string
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
  export type Filter = TypedDeferredTopicFilter<Event>
  export type Log = TypedEventLog<Event>
  export type LogDescription = TypedLogDescription<Event>
}

export namespace ProtocolUpdatedEvent {
  export type InputTuple = [operator: AddressLike, newProtocol: AddressLike]
  export type OutputTuple = [operator: string, newProtocol: string]
  export interface OutputObject {
    operator: string
    newProtocol: string
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
  export type Filter = TypedDeferredTopicFilter<Event>
  export type Log = TypedEventLog<Event>
  export type LogDescription = TypedLogDescription<Event>
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike]
  export type OutputTuple = [account: string]
  export interface OutputObject {
    account: string
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
  export type Filter = TypedDeferredTopicFilter<Event>
  export type Log = TypedEventLog<Event>
  export type LogDescription = TypedLogDescription<Event>
}

export namespace WithdrawEvent {
  export type InputTuple = [operator: AddressLike, receiver: AddressLike, token: AddressLike, amount: BigNumberish]
  export type OutputTuple = [operator: string, receiver: string, token: string, amount: bigint]
  export interface OutputObject {
    operator: string
    receiver: string
    token: string
    amount: bigint
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
  export type Filter = TypedDeferredTopicFilter<Event>
  export type Log = TypedEventLog<Event>
  export type LogDescription = TypedLogDescription<Event>
}

export interface OptimexLiquidator extends BaseContract {
  connect(runner?: ContractRunner | null): OptimexLiquidator
  waitForDeployment(): Promise<this>

  interface: OptimexLiquidatorInterface

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>

  MIN_REQUIRED_SIGNATURES: TypedContractMethod<[], [bigint], 'view'>

  deposit: TypedContractMethod<[token: AddressLike, amount: BigNumberish], [void], 'nonpayable'>

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string
        name: string
        version: string
        chainId: bigint
        verifyingContract: string
        salt: string
        extensions: bigint[]
      },
    ],
    'view'
  >

  getProtocol: TypedContractMethod<[], [string], 'view'>

  liquidationGateway: TypedContractMethod<[], [string], 'view'>

  optimexDomain: TypedContractMethod<[], [[string, string] & { name: string; version: string }], 'view'>

  pause: TypedContractMethod<[], [void], 'nonpayable'>

  paused: TypedContractMethod<[], [boolean], 'view'>

  payment: TypedContractMethod<
    [paymentRequest: PaymentRequestStruct, multisigAuth: MultisigAuthStruct],
    [void],
    'nonpayable'
  >

  setGateway: TypedContractMethod<[gateway: AddressLike], [void], 'nonpayable'>

  setProtocol: TypedContractMethod<[newProtocol: AddressLike], [void], 'nonpayable'>

  unpause: TypedContractMethod<[], [void], 'nonpayable'>

  withdraw: TypedContractMethod<[token: AddressLike, amount: BigNumberish, receiver: AddressLike], [void], 'nonpayable'>

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T

  getFunction(nameOrSignature: 'MIN_REQUIRED_SIGNATURES'): TypedContractMethod<[], [bigint], 'view'>
  getFunction(
    nameOrSignature: 'deposit'
  ): TypedContractMethod<[token: AddressLike, amount: BigNumberish], [void], 'nonpayable'>
  getFunction(nameOrSignature: 'eip712Domain'): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string
        name: string
        version: string
        chainId: bigint
        verifyingContract: string
        salt: string
        extensions: bigint[]
      },
    ],
    'view'
  >
  getFunction(nameOrSignature: 'getProtocol'): TypedContractMethod<[], [string], 'view'>
  getFunction(nameOrSignature: 'liquidationGateway'): TypedContractMethod<[], [string], 'view'>
  getFunction(
    nameOrSignature: 'optimexDomain'
  ): TypedContractMethod<[], [[string, string] & { name: string; version: string }], 'view'>
  getFunction(nameOrSignature: 'pause'): TypedContractMethod<[], [void], 'nonpayable'>
  getFunction(nameOrSignature: 'paused'): TypedContractMethod<[], [boolean], 'view'>
  getFunction(
    nameOrSignature: 'payment'
  ): TypedContractMethod<[paymentRequest: PaymentRequestStruct, multisigAuth: MultisigAuthStruct], [void], 'nonpayable'>
  getFunction(nameOrSignature: 'setGateway'): TypedContractMethod<[gateway: AddressLike], [void], 'nonpayable'>
  getFunction(nameOrSignature: 'setProtocol'): TypedContractMethod<[newProtocol: AddressLike], [void], 'nonpayable'>
  getFunction(nameOrSignature: 'unpause'): TypedContractMethod<[], [void], 'nonpayable'>
  getFunction(
    nameOrSignature: 'withdraw'
  ): TypedContractMethod<[token: AddressLike, amount: BigNumberish, receiver: AddressLike], [void], 'nonpayable'>

  getEvent(
    key: 'Deposit'
  ): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>
  getEvent(
    key: 'EIP712DomainChanged'
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >
  getEvent(
    key: 'LiquidationGatewayUpdated'
  ): TypedContractEvent<
    LiquidationGatewayUpdatedEvent.InputTuple,
    LiquidationGatewayUpdatedEvent.OutputTuple,
    LiquidationGatewayUpdatedEvent.OutputObject
  >
  getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>
  getEvent(
    key: 'ProtocolUpdated'
  ): TypedContractEvent<
    ProtocolUpdatedEvent.InputTuple,
    ProtocolUpdatedEvent.OutputTuple,
    ProtocolUpdatedEvent.OutputObject
  >
  getEvent(
    key: 'Unpaused'
  ): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>
  getEvent(
    key: 'Withdraw'
  ): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>

  filters: {
    'Deposit(address,address,uint256)': TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >
    Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>

    'EIP712DomainChanged()': TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >

    'LiquidationGatewayUpdated(address,address)': TypedContractEvent<
      LiquidationGatewayUpdatedEvent.InputTuple,
      LiquidationGatewayUpdatedEvent.OutputTuple,
      LiquidationGatewayUpdatedEvent.OutputObject
    >
    LiquidationGatewayUpdated: TypedContractEvent<
      LiquidationGatewayUpdatedEvent.InputTuple,
      LiquidationGatewayUpdatedEvent.OutputTuple,
      LiquidationGatewayUpdatedEvent.OutputObject
    >

    'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>
    Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>

    'ProtocolUpdated(address,address)': TypedContractEvent<
      ProtocolUpdatedEvent.InputTuple,
      ProtocolUpdatedEvent.OutputTuple,
      ProtocolUpdatedEvent.OutputObject
    >
    ProtocolUpdated: TypedContractEvent<
      ProtocolUpdatedEvent.InputTuple,
      ProtocolUpdatedEvent.OutputTuple,
      ProtocolUpdatedEvent.OutputObject
    >

    'Unpaused(address)': TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >
    Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>

    'Withdraw(address,address,address,uint256)': TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >
    Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>
  }
}
